"""Known vendor classifications for lobbying relevance scoring.

Research-based classification of firms from the Canadian Lobbying Registry.
Each firm was verified via web research (not classified by name alone).

Categories:
- CYBER: Pure cybersecurity vendor
- IT_SERVICES: IT consulting/services with cyber capability
- DEFENSE_IT: Defence contractor with IT/cyber work
- TELCO: Telecom with network security relevance
- IT_VENDOR: IT product vendor (hardware, software, cloud)
- IT_ASSOCIATION: Industry association representing IT/cyber sector

Used by enrichment.py to boost lobbying relevance scores for known
IT/cyber firms and to skip firms confirmed as NOT relevant.
"""

# Firms confirmed as relevant to cyber/IT procurement.
# Keys are substring patterns (lowercase) matched against firm names.
# Values are category strings used for scoring.
KNOWN_CYBER_IT_FIRMS: dict[str, str] = {
    # -- Pure Cybersecurity (CYBER) --
    "crowdstrike": "CYBER",
    "palo alto networks": "CYBER",
    "cyberark": "CYBER",
    "fortinet": "CYBER",
    "fireeye": "CYBER",
    "mandiant": "CYBER",
    "tenable": "CYBER",
    "sailpoint": "CYBER",
    "tanium": "CYBER",
    "splunk": "CYBER",
    "zscaler": "CYBER",
    "optiv": "CYBER",
    "securekey": "CYBER",
    "entrust": "CYBER",
    "check point software": "CYBER",
    "veeam": "CYBER",
    "esentire": "CYBER",
    "netsecure": "CYBER",
    "rsa, the security division": "CYBER",

    # -- IT Services / Consulting (IT_SERVICES) --
    "cgi information": "IT_SERVICES",
    "cgi group": "IT_SERVICES",
    "cgi canada": "IT_SERVICES",
    "accenture": "IT_SERVICES",
    "deloitte": "IT_SERVICES",
    "kpmg": "IT_SERVICES",
    "mnp": "IT_SERVICES",
    "pwc": "IT_SERVICES",
    "booz allen": "IT_SERVICES",
    "leidos": "IT_SERVICES",
    "saic": "IT_SERVICES",
    "science application": "IT_SERVICES",
    "unisys": "IT_SERVICES",
    "dxc technology": "IT_SERVICES",
    "valcom": "IT_SERVICES",
    "edgewater computer": "IT_SERVICES",
    "xwave": "IT_SERVICES",
    "compugen": "IT_SERVICES",
    "tata consultancy": "IT_SERVICES",
    "wipro": "IT_SERVICES",
    "serco": "IT_SERVICES",

    # -- Defence IT (DEFENSE_IT) --
    "general dynamics": "DEFENSE_IT",
    "lockheed martin": "DEFENSE_IT",
    "raytheon": "DEFENSE_IT",
    "thales": "DEFENSE_IT",
    "bae systems": "DEFENSE_IT",
    "rheinmetall": "DEFENSE_IT",
    "l-3 communications": "DEFENSE_IT",
    "l3 communications": "DEFENSE_IT",
    "l-3 technologies": "DEFENSE_IT",
    "northrop grumman": "DEFENSE_IT",
    "boeing": "DEFENSE_IT",
    "elbit": "DEFENSE_IT",
    "israel aircraft": "DEFENSE_IT",
    "kongsberg": "DEFENSE_IT",
    "saab": "DEFENSE_IT",
    "leonardo drs": "DEFENSE_IT",
    "drs technologies": "DEFENSE_IT",
    "ultra electronics": "DEFENSE_IT",
    "cae inc": "DEFENSE_IT",
    "gallium software": "DEFENSE_IT",
    "gallium visual": "DEFENSE_IT",
    "grey island": "DEFENSE_IT",
    "macdonald dettwiler": "DEFENSE_IT",
    "mda systems": "DEFENSE_IT",
    "mda geospatial": "DEFENSE_IT",
    "mda ltd": "DEFENSE_IT",
    "com dev": "DEFENSE_IT",
    "irving shipbuilding": "DEFENSE_IT",
    "airbus defence": "DEFENSE_IT",
    "safran": "DEFENSE_IT",
    "rockwell collins": "DEFENSE_IT",

    # -- Telecom (TELCO) --
    "telus": "TELCO",
    "bell canada": "TELCO",
    "rogers communication": "TELCO",
    "shaw communication": "TELCO",
    "bce inc": "TELCO",
    "bce mobile": "TELCO",
    "telesat": "TELCO",
    "xplornet": "TELCO",
    "cogeco": "TELCO",
    "sasktel": "TELCO",
    "mts allstream": "TELCO",
    "bell aliant": "TELCO",
    "teksavvy": "TELCO",
    "ssi micro": "TELCO",
    "ericsson": "TELCO",
    "nokia": "TELCO",
    "huawei": "TELCO",
    "samsung electronics": "TELCO",
    "motorola": "TELCO",
    "nortel": "TELCO",
    "newbridge networks": "TELCO",
    "avaya": "TELCO",
    "twilio": "TELCO",

    # -- IT Product Vendors (IT_VENDOR) --
    "microsoft": "IT_VENDOR",
    "ibm": "IT_VENDOR",
    "google canada": "IT_VENDOR",
    "google cloud": "IT_VENDOR",
    "amazon web services": "IT_VENDOR",
    "amazon corporate": "IT_VENDOR",
    "oracle": "IT_VENDOR",
    "sap canada": "IT_VENDOR",
    "cisco": "IT_VENDOR",
    "hewlett": "IT_VENDOR",
    "hp canada": "IT_VENDOR",
    "dell technologies": "IT_VENDOR",
    "dell products": "IT_VENDOR",
    "intel of canada": "IT_VENDOR",
    "salesforce": "IT_VENDOR",
    "servicenow": "IT_VENDOR",
    "vmware": "IT_VENDOR",
    "citrix": "IT_VENDOR",
    "nutanix": "IT_VENDOR",
    "juniper network": "IT_VENDOR",
    "bmc software": "IT_VENDOR",
    "ceridian": "IT_VENDOR",
    "opentext": "IT_VENDOR",
    "blackberry": "IT_VENDOR",
    "research in motion": "IT_VENDOR",
    "d-wave": "IT_VENDOR",
    "apple canada": "IT_VENDOR",
    "facebook": "IT_VENDOR",
    "meta ": "IT_VENDOR",
    "twitter canada": "IT_VENDOR",
    "shopify": "IT_VENDOR",
    "xerox": "IT_VENDOR",
    "lenovo": "IT_VENDOR",
    "fujitsu": "IT_VENDOR",
    "honeywell": "IT_VENDOR",
    "siemens canada": "IT_VENDOR",
    "siemens business": "IT_VENDOR",
    "siemens electric": "IT_VENDOR",
    "pure storage": "IT_VENDOR",
    "rubrik": "IT_VENDOR",
    "uipath": "IT_VENDOR",
    "element ai": "IT_VENDOR",
    "paypal": "IT_VENDOR",

    # -- IT Industry Associations (IT_ASSOCIATION) --
    "technation": "IT_ASSOCIATION",
    "information technology association": "IT_ASSOCIATION",
    "canadian association of defence and security": "IT_ASSOCIATION",
    "canadian internet registration": "IT_ASSOCIATION",
    "digital id and authentication council": "IT_ASSOCIATION",
    "digital identity laboratory": "IT_ASSOCIATION",
}


# Firms confirmed as NOT relevant to cyber/IT procurement.
# These lobby on subjects that overlap with IT codes (defence, telecom,
# science & tech) but are not in the IT/cyber industry.
NOT_RELEVANT_FIRMS: set[str] = {
    # Healthcare / Pharma
    "Canadian Medical Association",
    "CANADIAN CANCER SOCIETY",
    "Canadian Dental Association",
    "Canadian Nurses Association",
    "GlaxoSmithKline Inc.",
    "Sanofi Pasteur",
    "Innovative Medicines Canada",
    "Multiple Sclerosis Society of Canada",
    "Heart and Stroke Foundation of Canada",
    "Hoffmann-La Roche Limited",
    "McKesson Canada",
    "Apotex Inc.",
    "Eli Lilly Canada Inc.",
    "Novartis Pharmaceuticals Canada Inc.",
    "AstraZeneca Canada Inc.",
    "Amgen Canada Inc.",
    "Lundbeck Canada Inc.",
    "Pfizer Canada ULC",
    "Janssen Inc.",
    "Bayer Inc.",
    "Canadian Generic Pharmaceutical Association (CGPA)",
    "Canadian HIV/AIDS Legal Network",
    "Best Medicines Coalition",
    "Diabetes Canada",
    "Juvenile Diabetes Research Foundation",
    "Amyotrophic Lateral Sclerosis Society of Canada",
    "Canadian Psychological Association",
    "Canadian Chiropractic Association",

    # Agriculture / Food
    "Canadian Federation of Agriculture",
    "Dairy Farmers of Canada",
    "Canadian Aquaculture Industry Alliance",
    "Canadian Cattlemens' Association",
    "Canadian Canola Growers Association",
    "Canadian Seed Trade Association",
    "CROPLIFE CANADA",
    "Gay Lea Foods Co-operative Ltd",
    "Canadian Horticultural Council",
    "BC Dairy Association",
    "Canadian Poultry and Egg Processors Council",
    "KRAFT CANADA INC. (KCI)",
    "Loblaw Companies Limited",
    "FOOD AND CONSUMER PRODUCTS OF CANADA",
    "BREWERS ASSOCIATION OF CANADA",
    "Canadian Produce Marketing Association",
    "Canadian Seed Growers' Association",

    # Energy / Mining / Oil & Gas
    "Canadian Association of Petroleum Producers",
    "Enbridge Inc.",
    "Suncor Energy Inc.",
    "Cenovus Energy Inc.",
    "ENCANA CORPORATION",
    "Imperial Oil Limited",
    "Shell Canada Limited",
    "Chevron Canada Limited",
    "CONOCO PHILLIPS CANADA",
    "CAMECO CORPORATION",
    "Teck Resources Limited",
    "AltaGas Ltd.",
    "NOVA Chemicals Corporation",
    "TransCanada Corporation",
    "TC Energy Corporation",
    "Spectra Energy Transmission",
    "CANADIAN ELECTRICITY ASSOCIATION",
    "Canadian Gas Association",
    "CANADIAN ENERGY PIPELINE ASSOCIATION",
    "Ontario Power Generation Inc.",
    "Canadian Nuclear Association",
    "Vale Canada Ltd.",

    # Universities / Education
    "University of Alberta",
    "UNIVERSITY OF TORONTO",
    "University of Waterloo",
    "University of Calgary",
    "Queen's University",
    "York University",
    "McMaster University",
    "University of Victoria",
    "Dalhousie University",
    "The University of British Columbia",
    "University of Saskatchewan",
    "University of Manitoba",
    "McGill University",
    "Concordia University",
    "Brock University",
    "University of Lethbridge",
    "University of Ottawa",
    "University of Windsor",
    "Memorial University of Newfoundland",
    "Trent University",

    # Finance / Insurance / Banking
    "Canadian Bankers Association",
    "ROYAL BANK OF CANADA",
    "The Toronto-Dominion Bank",
    "CANADIAN IMPERIAL BANK OF COMMERCE ( CIBC)",
    "INSURANCE BUREAU OF CANADA",
    "Sun Life Financial Inc.",
    "Credit Union Central of Canada",
    "Canadian Life and Health Insurance Association Inc.",
    "Capital One Bank (Canada Branch)",
    "National Bank of Canada",
    "Investment Industry Association of Canada",

    # Transportation / Aerospace (non-IT)
    "Air Canada",
    "Greater Toronto Airports Authority",
    "NAV CANADA",
    "RAILWAY ASSOCIATION OF CANADA (THE) (RAC)",
    "Vancouver International Airport Authority",
    "Bombardier Inc.",
    "BELL HELICOPTER TEXTRON CANADA LIMITED",
    "CASCADE AEROSPACE INC.",
    "Magellan Aerospace Corporation",
    "Pratt & Whitney Canada",
    "Rolls-Royce Canada Limited",

    # Industry associations (non-IT)
    "Canadian Chamber of Commerce",
    "Canadian Federation of Independent Business (CFIB)",
    "Retail Council of Canada",
    "The Canadian Real Estate Association",
    "Canadian Steel Producers Association",
    "Forest Products Association of Canada",
    "Chemistry Industry Association of Canada",
    "Aerospace Industries Association of Canada",
    "CEMENT ASSOCIATION OF CANADA",
    "Canadian Construction Association",
    "Canadian Bar Association",
    "FEDERATION OF CANADIAN MUNICIPALITIES",
    "Alliance of Manufacturers & Exporters Canada (CME)",
    "Canadian Home Builders' Association",
    "Chartered Professional Accountants of Canada (CPA Canada)",
    "Canadian Labour Congress",

    # Media / Broadcasting
    "CTVglobemedia Inc.",
    "Corus Entertainment Inc.",
    "Writers Guild of Canada",
    "Canadian Association of Broadcasters",
    "Netflix Inc.",
    "Motion Picture Association - Canada",
    "Quebecor Inc.",
    "Entertainment Software Association of Canada",
    "Canadian Media Producers Association",
    "Music Canada",

    # Other
    "Saskatchewan Association of Rural Municipalities",
    "The Co-operators Group Limited",
    "3M CANADA COMPANY",
    "CANADIAN STANDARDS ASSOCIATION",
    "GENERAL MOTORS OF CANADA LIMITED",
    "General Motors of Canada Ltd.",
    "HONDA CANADA INC.",
    "FORD MOTOR COMPANY OF CANADA LTD.",
    "Chrysler Canada Inc.",
    "CANADIAN CATTLEMENS' ASSOCIATION",
    "TRIUMF",
    "Institute for Quantum Computing",
    "Canadian Microelectronics Corporation",
    "World Wildlife Fund Canada",
    "Environmental Defence Canada",
    "PEMBINA INSTITUTE",
    "David Suzuki Foundation",
    "Ecojustice Canada",
    "Imagine Canada",
    "GS1 Canada",
    "CALGARY ZOO",
    "Science World British Columbia",
    "Rick Hansen Foundation",
    "Canadian Alliance of Student Associations",
    "Genome Canada",
    "J.D. Irving, Limited",
    "Alcoa Canada Co.",
    "UNITED PARCEL SERVICE CANADA LTD.",
    "BALLARD POWER SYSTEMS",
    "AddEnergie",
    "Magna International Inc.",
    "Canadian Trucking Alliance",
}


# ---------------------------------------------------------------------------
# Exact-match set for highest-confidence IT/cyber/defence firms
# Added 2026-03-20 after LLM-assisted review of ~2300 Canadian Lobbying Registry firms.
#
# These are registry name strings (case-sensitive). Used in _find_lobbying()
# for a +5 score bonus (highest signal) when a lobbying registration comes
# from one of these confirmed vendors.
# ---------------------------------------------------------------------------

KNOWN_IT_CYBER_FIRMS_EXACT: frozenset[str] = frozenset({
    # -------------------------------------------------------------------------
    # Consulting / IT services
    # -------------------------------------------------------------------------
    "ACCENTURE INC.",
    "Accenture",
    "Accenture Inc.",
    "CGI",
    "CGI Group Inc",
    "CGI INFORMATION SYSTEMS AND MANAGEMENT CONSULTANTS INC.",
    "Carahsoft Technology Corp.",
    "DXC Technology",
    "MAXIMUS Canada",
    "MAXIMUS Inc.",
    "RedMane Technology Canada Inc.",
    "Unisys Canada Inc.",
    "ADGA Group Consultants Inc.",
    "Calian Group Ltd.",
    "Calian Ltd.",
    "CALIAN GROUP LTD.",
    "Compugen Inc.",
    "COMPUGEN INC.",
    "Softchoice Corporation",
    "SOFTCHOICE CORPORATION",
    "eSentire Inc.",

    # -------------------------------------------------------------------------
    # Cloud / software / SaaS
    # -------------------------------------------------------------------------
    "Amazon Web Services Canada, Inc.",
    "BMC Software Canada Inc.",
    "Canada Workday ULC",
    "Google Canada",
    "Google Canada Corporation",
    "Google Cloud Canada Corporation",
    "IBM CANADA LIMITED",
    "IBM CANADA LTD.",
    "IBM Canada Ltd.",
    "Microsoft Canada",
    "Microsoft Canada Co.",
    "Microsoft Canada Inc.",
    "MICROSOFT CANADA",
    "ORACLE CANADA",
    "Oracle Canada",
    "SAP CANADA INC.",
    "SAP Canada Inc.",
    "Salesforce",
    "Salesforce.com",
    "ServiceNow",
    "Shopify Inc.",
    "Software AG",
    "Twilio",
    "OpenText Corporation",
    "Open Text Corporation",
    "OPENTEXT CORPORATION",
    "Mitel Networks Corporation",
    "MITEL NETWORKS CORPORATION",
    "Kinaxis Inc.",
    "Info-Tech Research Group Inc. (Canada corporation)",

    # -------------------------------------------------------------------------
    # Cybersecurity
    # -------------------------------------------------------------------------
    "BlackBerry Limited",
    "BLACKBERRY LIMITED",
    "CyberArk Software Canada Inc.",
    "Palo Alto Networks",
    "Palo Alto Networks Inc.",
    "eSentire Inc.",

    # -------------------------------------------------------------------------
    # Networking / hardware
    # -------------------------------------------------------------------------
    "CISCO SYSTEMS CANADA INC.",
    "Cisco Systems Canada",
    "Cisco Systems Canada Co.",
    "Ericsson Canada Inc.",
    "Honeywell",
    "Siemens Canada Limited",
    "LinkedIn Technology Canada Inc",
    "DJI Technology Inc",
    "DJI Technology Inc.",

    # -------------------------------------------------------------------------
    # Telecom carriers
    # -------------------------------------------------------------------------
    "BELL CANADA",
    "Bell Aliant Inc.",
    "Bell Aliant Regional Communications",
    "Bell Canada",
    "Bell Canada, Inc.",
    "Cogeco Inc.",
    "Globalive Wireless Management Corp.",
    "ROGERS WIRELESS INC.",
    "Rogers Communications Inc.",
    "SHAW COMMUNICATIONS INC.",
    "Shaw Communications",
    "Shaw Communications Inc.",
    "Saskatchewan Telecommunications",
    "TekSavvy Solutions Inc.",
    "TELUS",
    "TELUS COMMUNICATIONS INC.",
    "TELUS Corporation",
    "Telus",
    "Telus Corporation",
    "Videotron Ltd.",
    "Xplornet Communications Inc.",

    # -------------------------------------------------------------------------
    # Satellite / space communications
    # -------------------------------------------------------------------------
    "TELESAT CANADA",
    "Telesat Canada",
    "Ciel Satellite Holdings Inc.",
    "Iridium Satellite Canada Limited",
    "MDA Geospatial Services Inc.",
    "NETWORK INNOVATIONS",
    "SES S.A.",
    "NAV CANADA",

    # -------------------------------------------------------------------------
    # Defence / aerospace technology
    # -------------------------------------------------------------------------
    "BAE SYSTEMS",
    "BELL HELICOPTER TEXTRON CANADA LIMITED",
    "Bell Helicopter Textron Canada limitée",
    "Bell Textron Canada Limited",
    "BOMBARDIER AEROSPACE",
    "BOMBARDIER AEROSPACE DEFENCE SERVICES",
    "BOMBARDIER INC.",
    "Bombardier Inc.",
    "CAE INC.",
    "CAE Inc.",
    "CAE inc.",
    "cae inc.",
    "CASCADE AEROSPACE INC.",
    "DRS EW & NETWORK SYSTEMS, INC",
    "GENERAL DYNAMICS CANADA",
    "GENERAL DYNAMICS LAND SYSTEMS - CANADA CORPORATION",
    "General Dynamics C4 Systems",
    "General Dynamics Land Systems-Canada",
    "General Dynamics Ordnance & Tactical Systems Canada Inc.",
    "General Dynamics Ordnance and Tactical Systems",
    "General Dynamics Ordnance and Tactical Systems - Canada Inc.",
    "Goodrich Aerospace Canada Ltd.",
    "KONGSBERG DEFENCE SYSTEMS",
    "Kongsberg Geospatial",
    "LOCKHEED MARTIN AERONAUTICS CO.",
    "LOCKHEED MARTIN AERONAUTICS COMPANY",
    "LOCKHEED MARTIN CANADA",
    "LOCKHEED MARTIN CANADA INC.",
    "LOCKHEED MARTIN MISSILES & FIRE CONTROL",
    "Lockheed Martin Canada",
    "Lockheed Martin Maritime Systems and Training",
    "Lockheed Martin Rotary & Mission Systems - Undersea Surveillance Systems",
    "MAGELLAN AEROSPACE CORPORATION",
    "Magellan Aerospace Corporation",
    "Pratt & Whitney Canada",
    "Provincial Aerospace",
    "Provincial Aerospace Limited",
    "Provincial Aerospace Ltd",
    "RHEINMETALL CANADA ",
    "Rheinmetall Canada",
    "Rheinmetall Canada Inc.",
    "Rheinmetall MAN Military Vehicles Canada Ltd. (RMMV)",
    "Raytheon Canada Limited",
    "Raytheon International Incorporated",
    "SPAR Aerospace Limited",
    "Thales Canada",
    "Thales Canada Inc",
    "Thales Canada Inc.",
    "Vector Aerospace Corporation",
})


def is_known_it_firm(firm_name: str) -> bool:
    """Return True if the firm name is a confirmed IT/cyber/defence vendor.

    Tries exact match first, then stripped whitespace variant.
    For substring matching, use KNOWN_CYBER_IT_FIRMS dict instead.
    """
    return firm_name in KNOWN_IT_CYBER_FIRMS_EXACT or firm_name.strip() in KNOWN_IT_CYBER_FIRMS_EXACT
